ignore = [
    "turbo_docs.toml",
    "__pycache__",
    "venv",
    "build",
    "dist",
    "*.egg-info",
    ".git",
    "data",
    "scripts",
    "*.ipynb",
    "LICENSE",
    ".gitignore",
    ".env",
    ".mypy_cache",
]
